## 
ikuai-url: http://192.168.1.1 # 爱快网页控制台登陆地址 结尾不要加 "/"，如在爱快docker内运行，网关就是爱快地址，可以不写，如不填写，则使用第一个接口的网关地址，
username: admin # ikuai username 爱快登陆用户名
password: mengna11  # ikuai user password爱快登陆密码
cron: 0 7 * * * # crontab 执行更新的周期 格式为linux crontab 格式 注意时区问题，也可以用  @every 24h00m00s  表示每间隔24小时执行一次
AddErrRetryWait: 10s # 自动重试时间间隔 时间格式为 10s  120s
AddWait: 1s # 添加规则后等待时间 等待爱快反应 适合性能低的设备
stream-domain:      # 域名分流 可选功能，优先级比ip分流高

  # 下面是自动走wan1直连的，
  - interface: wan1
    src-addr: 192.168.1.10-192.168.1.254
    # 作者自己维护的自定义的域名列表 主要存放github的镜像网站等国内可以直连的镜像或其他类型域名
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/joyanhui/ikuai-bypass/main/private/direct-domain-list.txt
    tag: private_direct
  - interface: wan1
    src-addr: 192.168.1.10-192.168.1.254 
  #  china-list 网址列表较大，不建议启用,在部分ikuai设备上可能会导致维护的时候超时出错。
    url:  https://mirror.ghproxy.com/https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/china-list.txt
    tag: cn


